export const PLAYERS_LIST = 'AAP/USERS/PLAYERS_LIST';
export const UPDATE_PLAYERS_LIST = 'AAP/USERS/UPDATE_PLAYERS_LIST';
export const ADD_PLAYER = 'AAP/USERS/ADD_PLAYER';
export const UPDATE_PLAYER = 'AAP/USERS/UPDATE_PLAYER';
export const DELETE_PLAYER = 'AAP/USERS/DELETE_PLAYER';